version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: migrate_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: migrate_db
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: